const mock = [
  {
    id: 1,
    name: "Beautiful Scarf",
    price: 213.44,
    quantity: 12,
    picture: "beautiful-scarf.jpg",
    sold: 554,
  },
  {
    id: 2,
    name: "Leash Toy",
    price: 113.44,
    quantity: 756,
    picture: "leash-toy.jpg",
    sold: 256,
  },
  {
    id: 3,
    name: "Orange Ball",
    price: 100,
    quantity: 1654,
    picture: "orange-ball.jpg",
    sold: 10,
  },
  {
    id: 4,
    name: "Rope",
    price: 98,
    quantity: 1232,
    picture: "rope.jpg",
    sold: 845,
  },
  {
    id: 5,
    name: "Seahorse",
    price: 55.99,
    quantity: 101,
    picture: "seahorse.jpg",
    sold: 553,
  },
  {
    id: 6,
    name: "Small Leash",
    price: 59.99,
    quantity: 22,
    picture: "small-leash.jpg",
    sold: 147,
  },
  {
    id: 7,
    name: "Super Ball",
    price: 1930.45,
    quantity: 25,
    picture: "super-ball.jpg",
    sold: 1054,
  },
  {
    id: 8,
    name: "Tennis Ball",
    price: 2500,
    quantity: 55,
    picture: "tennis-ball.jpg",
    sold: 356,
  },
  {
    id: 9,
    name: "Yellow Ball",
    price: 12500,
    quantity: 54,
    picture: "yellow-ball.jpg",
    sold: 935,
  },
];

export default mock;
